"""Generate a standalone, git-repo-shaped Databricks App project for a graph.

This is the "agents on apps" deploy path — an OPTIONAL alternative to Model
Serving (``main.py:deploy_graph``).  Instead of logging an MLflow model and
creating a serving endpoint, it emits a self-contained app project that wraps
the compiled graph in MLflow's ``AgentServer`` (exposing ``/invocations``),
uploads it to a workspace folder, and deploys it as a Databricks App.

The generated project is a proper git repo (README, .gitignore, databricks.yml,
app.yaml) so a team can later push it to GitHub and switch the app to
git-backed deployment for collaboration.

The shared load/compile/run/stream logic lives in ``backend.agent_runtime``;
the generated ``agent/agent.py`` registers thin ``@invoke()``/``@stream()``
handlers over it.

NOTE (future deprecation): once agents-on-apps replaces Model Serving, flip the
frontend deploy-target default to "app" and eventually remove the serving path.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from .deploy_resources import _persist_mcp_tool_metadata
from .schema import GraphDef

# Backend modules the generated app does NOT need at runtime (FastAPI-app-only
# concerns).  Everything else in backend/ is copied so the graph can compile.
_BACKEND_DIR = Path(__file__).parent
_EXCLUDE_MODULES = (
    "mlruns", "__pycache__", "static", "*.pyc", "*.db",
    "main.py", "ai_chat.py", "eval.py", "discovery.py", "setup.py",
    "mlflow_model.py", "app_deploy.py", "deploy_resources.py", "tests",
)


@dataclass
class AppDeployConfig:
    """Inputs for generating an agent-app project."""

    app_name: str
    auth_mode: str = "obo"
    # PAT used to pre-discover MCP tool metadata under the user's identity
    # (falls back to SP inside _persist_mcp_tool_metadata when empty).
    pat: str = ""
    # Lakebase env vars to bake into the deployment (LAKEBASE_ENDPOINT, etc.).
    lakebase_env: dict[str, str] = field(default_factory=dict)
    # databricks-sdk AppResource objects + user_api_scopes for databricks.yml.
    resources: list = field(default_factory=list)
    user_api_scopes: list[str] = field(default_factory=list)


# ── File templates ───────────────────────────────────────────────────────

_START_SERVER_PY = '''\
"""Entry point: MLflow AgentServer exposing /invocations for this agent.

Generated by AgentSweet. The agent logic lives in ``agent/agent.py``, which
registers @invoke()/@stream() handlers on import.
"""

from mlflow.genai.agent_server import AgentServer
from starlette.middleware.base import BaseHTTPMiddleware

from backend.auth import set_user_token

agent_server = AgentServer("ResponsesAgent")

# Importing the module registers the handlers on ``agent_server``.
import agent.agent  # noqa: E402,F401

app = agent_server.app


class _OBOMiddleware(BaseHTTPMiddleware):
    """Capture the user's OBO token from the Apps proxy so data-access nodes
    can route through managed MCP (mcp.* scopes) with the caller's identity.

    AgentServer has its own FastAPI app and does not include AgentSweet's
    OBO middleware; without this, get_user_token() is None and tool factories
    fall back to the direct-SDK path (wrong for an app with mcp.* scopes).
    """

    async def dispatch(self, request, call_next):
        set_user_token(request.headers.get("x-forwarded-access-token"))
        return await call_next(request)


app.add_middleware(_OBOMiddleware)

if __name__ == "__main__":
    agent_server.run(app_import_string="start_server:app")
'''

_AGENT_PY = '''\
"""Agent handlers wrapping the compiled LangGraph agent for MLflow AgentServer.

Reuses ``backend.agent_runtime`` — the same load/compile/run/stream code the
Model Serving path uses — so behavior is identical across deploy targets.
"""

import os

from mlflow.genai.agent_server import invoke, stream

from backend.agent_runtime import load_agent_from_file, run_agent, stream_agent

# serving=False: this is a Databricks App, so data access routes through
# managed MCP using the app's mcp.* OBO scopes (not direct-SDK scopes).
_GRAPH_DEF_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "graph_def.json")
_AGENT = load_agent_from_file(_GRAPH_DEF_PATH, serving=False)


@invoke()
def handle(request):
    return run_agent(_AGENT, request)


@stream()
def handle_stream(request):
    yield from stream_agent(_AGENT, request)
'''

_APP_YAML = '''\
# Databricks Apps runtime config. DATABRICKS_HOST/CLIENT_ID/CLIENT_SECRET are
# auto-injected; the user's OBO token arrives as x-forwarded-access-token.
command:
  - python
  - start_server.py
'''

_GITIGNORE = '''\
__pycache__/
*.pyc
*.db
.venv/
.env
.databricks/
'''

_README_MD = '''\
# {app_name}

An AI agent generated by **AgentSweet** and deployed as a **Databricks App**
(agents on apps). It exposes an MLflow `AgentServer` at `POST /invocations`
(OpenAI Responses schema, with `stream: true` for SSE streaming).

## Project layout

```
start_server.py       MLflow AgentServer entry point (/invocations)
agent/agent.py        @invoke()/@stream() handlers over the compiled graph
graph_def.json        the agent graph definition
backend/              runtime: graph_builder, nodes, tools, auth, agent_runtime
app.yaml              Databricks Apps runtime command
databricks.yml        bundle config: app resources + user_api_scopes
requirements.txt      pinned Python dependencies
```

## Local development

```bash
pip install -r requirements.txt
python start_server.py            # serves on http://localhost:8000
curl -N localhost:8000/invocations \\
  -H "Content-Type: application/json" \\
  -d '{{"input":[{{"role":"user","content":"hello"}}]}}'
```

## Move to a GitHub-backed app (recommended for team collaboration)

This project was deployed from workspace files. To collaborate as a team
(e.g. add a frontend), promote it to a git-backed Databricks App:

1. **Push to GitHub** — from this folder:

   ```bash
   git init
   git add .
   git commit -m "Initial agent app"
   git remote add origin https://github.com/<org>/<repo>.git
   git push -u origin main
   ```

   (If you started from the workspace copy, first export it:
   `databricks workspace export-dir <workspace-path> ./{app_name}`.)

2. **Point the app at the repo** — in the Databricks Apps UI, edit the app →
   configure Git → enter the repo URL + branch. For private repos, add a Git
   credential for the app's service principal. Enable **auto-deploy on push**
   so merges to your branch redeploy automatically.

3. **Iterate** — teammates clone the repo, make changes, and push; the app
   redeploys from git. No more manual workspace-file syncs.
'''


def _resource_to_yaml(resource) -> dict:
    """Serialize a databricks-sdk AppResource to a plain dict for databricks.yml.

    Uses the SDK's own ``as_dict()`` so the shape always matches the API.
    """
    return resource.as_dict()


def _databricks_yml(cfg: AppDeployConfig) -> str:
    """Build the bundle config for a future ``databricks bundle deploy``.

    The SDK deploy path (main.py) does not consume this file — it configures
    the app directly — but a git-backed workflow uses it, so we keep the same
    resources + scopes as the single source of truth.
    """
    app_block: dict = {
        "name": cfg.app_name,
        "source_code_path": ".",
        "config": {
            "command": ["python", "start_server.py"],
        },
    }
    if cfg.user_api_scopes:
        app_block["user_api_scopes"] = list(cfg.user_api_scopes)
    if cfg.resources:
        app_block["resources"] = [_resource_to_yaml(r) for r in cfg.resources]

    doc = {
        "bundle": {"name": cfg.app_name},
        "resources": {"apps": {cfg.app_name.replace("-", "_"): app_block}},
        "targets": {"dev": {"default": True}},
    }
    return yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)


def generate_app_project(graph: GraphDef, cfg: AppDeployConfig, dest: Path) -> Path:
    """Write the full agent-app project into ``dest`` and return it.

    Steps:
    1. Deep-copy the graph, stamp auth_mode, pre-discover + persist MCP tools.
    2. Write graph_def.json + all project files.
    3. Copy the backend/ runtime subset (excludes FastAPI-app-only modules).
    """
    dest.mkdir(parents=True, exist_ok=True)

    # 1. Enrich the graph exactly like the serving path does.
    graph_for_artifact = graph.model_copy(deep=True)
    graph_for_artifact.auth_mode = cfg.auth_mode
    _persist_mcp_tool_metadata(graph_for_artifact, pat=cfg.pat)

    # 2. graph_def.json
    (dest / "graph_def.json").write_text(graph_for_artifact.model_dump_json())

    # 3. Entry point + handlers
    (dest / "start_server.py").write_text(_START_SERVER_PY)
    agent_pkg = dest / "agent"
    agent_pkg.mkdir(exist_ok=True)
    (agent_pkg / "__init__.py").write_text("")
    (agent_pkg / "agent.py").write_text(_AGENT_PY)

    # 4. Config + docs
    (dest / "app.yaml").write_text(_APP_YAML)
    (dest / "databricks.yml").write_text(_databricks_yml(cfg))
    (dest / ".gitignore").write_text(_GITIGNORE)
    (dest / "README.md").write_text(_README_MD.format(app_name=cfg.app_name))

    # 5. requirements.txt — reuse the already-compiled serving pin file.
    req_src = _BACKEND_DIR.parent / "requirements-serving.txt"
    if req_src.exists():
        shutil.copy(req_src, dest / "requirements.txt")
    else:
        raise FileNotFoundError(
            "requirements-serving.txt not found. Run: "
            "uv pip compile pyproject.toml -o requirements-serving.txt "
            "--python-version 3.11"
        )

    # 6. backend/ runtime subset
    shutil.copytree(
        _BACKEND_DIR,
        dest / "backend",
        ignore=shutil.ignore_patterns(*_EXCLUDE_MODULES),
    )

    return dest
