"""Generate a Databricks deployment notebook for an Agent Builder graph.

The notebook is self-contained: it installs dependencies, logs the model
to MLflow, registers it in Unity Catalog, and creates a serving endpoint.
Users run it in their own workspace with their own credentials.
"""

from __future__ import annotations

import json

from .schema import DeployNotebookRequest, GraphDef

# Git install source for the agent-builder-app package
_PIP_INSTALL_SOURCE = "git+https://github.com/btbeal-db/agent-builder-app.git"

# Config field → (resource class name, constructor kwarg)
_RESOURCE_MAP: dict[str, tuple[str, str]] = {
    "endpoint": ("DatabricksServingEndpoint", "endpoint_name"),
    "endpoint_name": ("DatabricksServingEndpoint", "endpoint_name"),
    "index_name": ("DatabricksVectorSearchIndex", "index_name"),
    "room_id": ("DatabricksGenieSpace", "genie_space_id"),
    "table_name": ("DatabricksTable", "table_name"),
    "function_name": ("DatabricksFunction", "function_name"),
}


def _resources_source(graph: GraphDef) -> str:
    """Generate Python source code for the MLflow resource declarations."""
    lines: list[str] = []
    seen: set[tuple[str, str]] = set()

    for node in graph.nodes:
        for config_key, (cls_name, kwarg) in _RESOURCE_MAP.items():
            value = node.config.get(config_key)
            if value and (config_key, value) not in seen:
                seen.add((config_key, value))
                lines.append(f'    {cls_name}({kwarg}="{value}"),')

    if not lines:
        return "resources = []"
    return "resources = [\n" + "\n".join(lines) + "\n]"


def _cell(code: str) -> str:
    """Format a code cell."""
    return code.strip()


def _md(text: str) -> str:
    """Format a markdown cell."""
    lines = text.strip().split("\n")
    return "\n".join(f"# MAGIC {line}" if line.strip() else "# MAGIC" for line in lines)


def _join_cells(cells: list[str]) -> str:
    """Join cells with Databricks notebook separators."""
    header = "# Databricks notebook source"
    sep = "\n\n# COMMAND ----------\n\n"
    return header + sep + sep.join(cells) + "\n"


def generate_deploy_notebook(req: DeployNotebookRequest) -> str:
    """Build the full notebook content as a Databricks .py notebook string."""

    graph_json = json.dumps(req.graph.model_dump(), indent=2)
    # Triple single quotes are safe for JSON (JSON only uses double quotes)
    escaped_json = graph_json

    model_parts = req.model_name.split(".")
    endpoint_name = model_parts[-1].replace("_", "-") if model_parts else "my-agent"

    env_vars_dict = {
        "ENABLE_MLFLOW_TRACING": "true",
    }
    if req.lakebase_conn_string:
        env_vars_dict["LAKEBASE_CONN_STRING"] = req.lakebase_conn_string

    cells: list[str] = []

    # ── Cell 1: Title ────────────────────────────────────────────────
    cells.append(_md(f"""\
%md
# Deploy Agent: `{req.model_name}`

This notebook was generated by the **Agent Builder** app.
Run all cells to log, register, and deploy your agent as a Model Serving endpoint.

**What this notebook does:**
1. Installs the `agent-builder-app` package
2. Logs the agent graph as an MLflow model with resource declarations
3. Registers the model in Unity Catalog
4. Creates a Model Serving endpoint with AI Gateway"""))

    # ── Cell 2: Install dependencies ─────────────────────────────────
    cells.append(_cell(f"""\
%pip install "{_PIP_INSTALL_SOURCE}" --quiet
dbutils.library.restartPython()"""))

    # ── Cell 3: Configuration ────────────────────────────────────────
    cells.append(_md("""\
%md
## Configuration
Edit these values if needed before running the remaining cells."""))

    cells.append(_cell(f"""\
MODEL_NAME = "{req.model_name}"
EXPERIMENT_PATH = "{req.experiment_path}"
LAKEBASE_CONN_STRING = "{req.lakebase_conn_string}"
ENDPOINT_NAME = "{endpoint_name}" """))

    # ── Cell 4: Log model ────────────────────────────────────────────
    cells.append(_md("""\
%md
## Step 1: Log Model to MLflow
This writes the graph definition, model wrapper, and resource declarations to an MLflow experiment."""))

    cells.append(_cell(f"""\
import json
import tempfile
from pathlib import Path

import mlflow
from mlflow.models.resources import (
    DatabricksFunction,
    DatabricksGenieSpace,
    DatabricksServingEndpoint,
    DatabricksTable,
    DatabricksVectorSearchIndex,
)

# Graph definition (generated by Agent Builder)
GRAPH_DEF = json.loads('''
{escaped_json}
''')

# Resource declarations for automatic auth passthrough
{_resources_source(req.graph)}

# Write graph def to temp file
with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
    json.dump(GRAPH_DEF, f)
    graph_def_path = f.name

# Locate the installed package for code_paths and model wrapper
import shutil
import backend
backend_dir = Path(backend.__file__).parent
python_model_path = str(backend_dir / "mlflow_model.py")

# Copy backend package (excluding static files) for code_paths
tmp_code = Path(tempfile.mkdtemp()) / "backend"
shutil.copytree(
    backend_dir, tmp_code,
    ignore=shutil.ignore_patterns("__pycache__", "static", "*.pyc", "mlflow_model.py"),
)

# Log the model
mlflow.set_tracking_uri("databricks")
mlflow.set_registry_uri("databricks-uc")
experiment = mlflow.set_experiment(EXPERIMENT_PATH)

with mlflow.start_run() as run:
    model_info = mlflow.pyfunc.log_model(
        artifact_path="agent",
        python_model=python_model_path,
        artifacts={{"graph_def": graph_def_path}},
        code_paths=[str(tmp_code)],
        resources=resources if resources else None,
    )
    run_id = run.info.run_id

print(f"Model logged. Run ID: {{run_id}}")
print(f"Model URI: {{model_info.model_uri}}")"""))

    # ── Cell 5: Register model ───────────────────────────────────────
    cells.append(_md("""\
%md
## Step 2: Register in Unity Catalog"""))

    cells.append(_cell("""\
mv = mlflow.register_model(
    model_uri=model_info.model_uri,
    name=MODEL_NAME,
)
print(f"Registered {MODEL_NAME} version {mv.version}")"""))

    # ── Cell 6: Create endpoint ──────────────────────────────────────
    cells.append(_md("""\
%md
## Step 3: Create Serving Endpoint
This creates (or updates) a Model Serving endpoint with AI Gateway and inference tables enabled."""))

    env_vars_source = json.dumps(env_vars_dict, indent=8)

    cells.append(_cell(f"""\
from databricks.sdk import WorkspaceClient
from databricks.sdk.errors import ResourceAlreadyExists
from databricks.sdk.service.serving import (
    AiGatewayConfig,
    AiGatewayInferenceTableConfig,
    EndpointCoreConfigInput,
    ServedEntityInput,
)

w = WorkspaceClient()

env_vars = {env_vars_source}
env_vars["MLFLOW_EXPERIMENT_ID"] = experiment.experiment_id

served_entity = ServedEntityInput(
    entity_name=MODEL_NAME,
    entity_version=str(mv.version),
    environment_vars=env_vars,
    scale_to_zero_enabled=True,
    workload_size="Small",
)

parts = MODEL_NAME.split(".")
ai_gateway = AiGatewayConfig(
    inference_table_config=AiGatewayInferenceTableConfig(
        catalog_name=parts[0],
        schema_name=parts[1],
        table_name_prefix=ENDPOINT_NAME,
        enabled=True,
    ),
)

try:
    w.serving_endpoints.create(
        name=ENDPOINT_NAME,
        config=EndpointCoreConfigInput(
            name=ENDPOINT_NAME,
            served_entities=[served_entity],
        ),
        ai_gateway=ai_gateway,
    )
    print(f"Creating endpoint '{{ENDPOINT_NAME}}'...")
except ResourceAlreadyExists:
    w.serving_endpoints.update_config(
        name=ENDPOINT_NAME,
        served_entities=[served_entity],
    )
    w.serving_endpoints.put_ai_gateway(
        name=ENDPOINT_NAME,
        inference_table_config=AiGatewayInferenceTableConfig(
            catalog_name=parts[0],
            schema_name=parts[1],
            table_name_prefix=ENDPOINT_NAME,
            enabled=True,
        ),
    )
    print(f"Updating existing endpoint '{{ENDPOINT_NAME}}'...")

host = w.config.host.rstrip("/")
print(f"\\nEndpoint URL: {{host}}/serving-endpoints/{{ENDPOINT_NAME}}/invocations")
print(f"Playground: {{host}}/ml/endpoints/{{ENDPOINT_NAME}}")"""))

    return _join_cells(cells)
